//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace migratedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoReplyRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoReplyRule()
        {
            this.AutoReplyKeywords = new HashSet<AutoReplyKeyword>();
            this.AutoReplyMessages = new HashSet<AutoReplyMessage>();
            this.AutoReplyRegexes = new HashSet<AutoReplyRegex>();
        }
    
        public long Id { get; set; }
        public long MerchantId { get; set; }
        public string Source { get; set; }
        public int RuleType { get; set; }
        public string Description { get; set; }
        public bool ReplyAll { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoReplyKeyword> AutoReplyKeywords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoReplyMessage> AutoReplyMessages { get; set; }
        public virtual Merchant Merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoReplyRegex> AutoReplyRegexes { get; set; }
    }
}
