//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace migratedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class CannedReplyAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CannedReplyAnswer()
        {
            this.CannedReplyQuestions = new HashSet<CannedReplyQuestion>();
        }
    
        public long Id { get; set; }
        public long MerchantId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string CategoryName { get; set; }
        public string ReplyContent { get; set; }
        public bool IsAutoReplyEnabled { get; set; }
        public System.DateTimeOffset CreationTime { get; set; }
        public string CS_ReplyContent { get; set; }
        public int Frequency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CannedReplyQuestion> CannedReplyQuestions { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
