//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace migratedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class CannedReplyQuestion
    {
        public long Id { get; set; }
        public long MerchantId { get; set; }
        public Nullable<long> UserId { get; set; }
        public long CannedReplyAnswerId { get; set; }
        public string Question { get; set; }
        public string CS_Question { get; set; }
        public System.DateTimeOffset CreationTime { get; set; }
    
        public virtual CannedReplyAnswer CannedReplyAnswer { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
